<?php

declare(strict_types=1);

use App\Spiders\MyCharacterSpider;
use PHPUnit\Framework\TestCase;
use RoachPHP\Http\Request;

class MyCharacterSpiderTest extends TestCase
{
    private string $myCharacterId;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        /** @var string myCharacterId */
        $this->myCharacterId = getenv('MY_CHARACTER_ID');
    }

    /**
     * @return Request[]
     */
    public function testParse(): array
    {
        $charUrl = MyCharacterSpider::START_URL . '/' . $this->myCharacterId;

        $request = [
            new Request(
                'GET',
                $charUrl,
                [$this, 'parse']
            ),
        ];

        $result = false;
        self::assertEquals(true, $result);
    }
}
